from assetmanager.models import * # import all models
from django.contrib import admin

admin.site.register(Datacentre)
admin.site.register(Serverroom)
admin.site.register(Rack)
admin.site.register(Device)
admin.site.register(Router)
admin.site.register(Server)
admin.site.register(Switch)
admin.site.register(KVM)
admin.site.register(UPS)
admin.site.register(Other)
admin.site.register(PDU)
admin.site.register(Subnet)
admin.site.register(Networkinterface)
admin.site.register(VM)
admin.site.register(DeviceFunction)
admin.site.register(DiskArray)
admin.site.register(NetworkHardInterface)
admin.site.register(RaidArray)
admin.site.register(Harddisk)
admin.site.register(Partition)
